spring:
  application:
    name: whiteboard

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
    open-in-view: false

  h2:
    console:
      enabled: true